### PR TITLE
Helpers: Autodetection of PhpStorm in Linux environment for Editor URI.

### PR DESCRIPTION
**Pull request by janbarasek**
- new feature
- BC break? yes

In a Linux environment or on a Mac, the default disk path to PhpStorm is always `/usr/local/bin/phpstorm`. This allows us to detect that PhpStorm is available and set the default path to the editor.

At the same time, on a Mac, all we have to do is set the URI and the click-through works immediately.

This feature was inspired by the implementation in PhpStan Pro.

Snímek obrazovky 2022-05-23 v 8 44 31

### CODE REVIEW

**Comment by dg** [comment]
This is a BC break, then file creation stops working.

**Comment by janbarasek** [comment]
@dg I fixed the editor URI string.

**Comment by dg** [comment]
PhpStorm can do this?

**Comment by dg** [comment]
Sure, you open an existing file. But it stops the file creation and editing features of open-editor.js. 

Or what it's good for `&search=%search&replace=%replace` inside `$editor = 'phpstorm://%action?file=%file&line=%line&search=%search&replace=%replace';`?

**Comment by janbarasek** [comment]
Sorry for the slower reply, I needed to thoroughly test all scenarios.

In the end, it looks like you can only send an action to PhpStorm via URL to open a file. So what about replacing the URI to only do the `open` action? Even so, this will solve most of the common cases when working with dump data.

**Pull request closed without merging**
