### PR TITLE
Saving and restoring of toggles

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by fprochazka** [comment]
Is it gonna remember toggles of data dump structures?

**Comment by dg** [comment]
Yes, try it.

**Comment by fprochazka** [comment]
If I have multiple datetime objects in another object, it remembers only the goggle state of the last one and ignores the others.

**Comment by dg** [comment]
Where? In arguments? Debug bar?

**Comment by fprochazka** [comment]
@dg In the panel, in identity dump. I have several datetime properties there.

**Comment by dg** [comment]
@fprochazka can you prepare minimal example?

**Pull request merged**
