### PR TITLE
Dumper: added ext-ds support

### LINKED ISSUE #472: ext-ds support
Instead of arrays I much prefer using specialized data structures from ext-ds extension:

- https://github.com/php-ds/ext-ds
- https://www.php.net/manual/en/book.ds.php
- https://pecl.php.net/package/ds

Unfortunately Tracy dumper seems unable to show me the contents of the data structures which often leads to important info to be missing on the exception screen.

If I understand Tracy correctly then this should be possible using [`\Tracy\Dumper::$objectExporters`](https://github.com/nette/tracy/blob/c0f21d61bec95984470eeceee7d3e4496f3dee7f/src/Tracy/Dumper/Dumper.php#L74).

### PR DESCRIPTION
**Pull request by enumag**
Closes #472

### CODE REVIEW

**Comment by enumag** [comment]
@dg The failure is not caused by my changes.

**Comment by dg** [comment]
Can you add a test?

**Comment by enumag** [comment]
The test would of course require ext-ds to be installed. I'm not sure how to add it on your GitHub Actions setup.

**Comment by dg** [comment]
In this way: https://github.com/nette/latte/blob/master/.github/workflows/tests.yml#L20

(Probably `extensions: ds`)

**Comment by enumag** [comment]
@dg How do I run the tests locally? I tried `composer tester` but it fails with

```
   Error: Interface 'JsonSerializable' not found
```

I have no idea why. I'm using json extension every day and in my code it always exists. So I'm very confused. Can you fix `composer tester` so that it would work?

**Comment by milo** [comment]
`vendor/bin/tester -C tests` should do the job

**Comment by dg** [comment]
ad JsonSerializable: what operating system are you using?

**Comment by enumag** [comment]
@dg Ubuntu but I don't think it's important. The issue is that nette/tester isn't using the system's default php.ini without the `-C` option so it didn't load any extensions. It is very counter-intuitive for someone not experienced with nette/tester.

**Comment by dg** [comment]
The point is, it works for me on Windows and I had no idea there is such a problem. 

This has to be solved with a custom php.ini, I'll fix it so please don't change the composer.json.

**Pull request merged**
