### PR TITLE
Fix opacity hover effect on panels

### PR DESCRIPTION
**Pull request by JanTvrdik**
All browsers except for Chrome have trouble rendering them.

### CODE REVIEW

**Comment by hrach** [comment]
I have no idea which issue are you trying to solve :-) For me, the opacity works ok in Firefox :-) I'm just curious, could you make a little screencast? :)

**Comment by JanTvrdik** [comment]
@hrach  [recording-2016-05-13-13310.zip](https://github.com/nette/tracy/files/263067/recording-2016-05-13-13310.zip)

**Comment by dg** [comment]
On Windows it is fine. Btw I had similar problem on one website with Chrome and solution was `	-webkit-backface-visibility: hidden`.

**Comment by JanTvrdik** [comment]
@dg I have Windows 10.

**Comment by dg** [comment]
Hmmm, me too. Windows 10, Firefox 45.0.2, now updated to 46.0.1 and no problems.

**Comment by JanTvrdik** [comment]
Latest Firefox, clean profile without any option changes, the transition without will-change is broken both on panels and bar.

tracy-ff

**Comment by dg** [comment]
What about change max opacity to 0.99?

**Comment by JanTvrdik** [comment]
What's the problem with will-change? Changing max opacity to 0.99 does not help.

**Comment by dg** [comment]
will-change. is ok, just this PR seems like bigger fix.

**Comment by JanTvrdik** [comment]
@dg Should I move the dragging optimization to another PR? I'm working now on bugfixing + optimizing `moveConstrains`

**Comment by hrach** [comment]
oh yeah, this will be probably some bug of graphic drivers & firefox, still :+1: if it works for you.

**Comment by JanTvrdik** [comment]
@dg This is now ready to merge from my point of view.

The last commit introduces a behavior change – panel can no longer be partially (20%) out of the window – this fixes issue with panels that were impossible to move because drag handler (h1) was out of the window.

**Comment by dg** [comment]
Thanks!

**Pull request merged**
