### PR TITLE
Dumper: default options in static vars

### PR DESCRIPTION
**Pull request by pkristian**
When some SQL fail, i needed to show whole query, so: need to configure truncate length in `\Tracy\Dumper::toHtml()` , so i did everything configurable

### CODE REVIEW

**Comment by dg** [comment]
Static vars are antipattern…

**Comment by janedbal** [comment]
I would love to have configurable these options.

**Comment by pkristian** [comment]
Similar variables are in `\Tracy\Debugger`, in fact i copied and altered it

**Comment by dg** [comment]
They are configurable, all methods accepts options.

**Comment by pkristian** [comment]
If there is another , more pleasing way, how to configure configure truncate- mainly for bluesreen purposes, i will be happy, if you will show me

**Comment by dg** [comment]
The way is to add $dumperOptions to BlueScreen.

**Comment by pkristian** [comment]
Doesnt sound bad, but wouldn't be nice to have this more global?

in BlueScreen, `public static $dumperOptions = [];` is fine, or how will you recommand it?

**Comment by dg** [comment]
Without static, you can access it via `Debugger::getBlueScreen()->dumperOptions`

**Comment by pkristian** [comment]
Sounds good, going on it

**Comment by pkristian** [comment]
oh, i just found in v 2.4.2 is nice thing ´\Tracy\Debugger::getBlueScreen()->maxLength´, just what i needed... so thx, David! :)

**Pull request closed without merging**
