### PR TITLE
Tracy\Bar's output can be disabled (closes #82)

### LINKED ISSUE #82: Tracy\Bar cannot be disabled
It would be nice to have an option for disabling Tracy\Bar's output.

The output is very long JavaScript and eg. on mobile devices it can breaks other JavaScript processing.

Also, see:

* http://forum.nette.org/cs/20733-jak-vypnout-debug-bar-pro-response
* https://www.google.cz/search?q=nette+disable+debug+bar+site:forum.nette.org

### PR DESCRIPTION
**Pull request by hranicka**
Closes #82

### CODE REVIEW

**Comment by bazo** [comment]
please merge this. disable/enable or hide/show are both good names. but it's a pain in the ass to develop a rest api with the bar output in the response

**Comment by dg** [comment]
@bazo Send the correct Content-Type header.

**Comment by bazo** [comment]
ok, that helped. but still, this can be a useful feature

**Comment by encero** [comment]
+1, i am already using forked version with this merged.

**Comment by hranicka** [comment]
Wait for v2.4 :)

**Pull request closed without merging**
