### PR TITLE
dump php://input in bluescreen

### PR DESCRIPTION
**Pull request by mzk**
add support for PATCH requests

- [ ] fix tests

Is this solution ok?

### CODE REVIEW

**Comment by JanTvrdik** [comment]
:-1:

**Comment by milo** [comment]
The body can be in MB. Some insight would be handy, but this is too much.

**Comment by JanTvrdik** [comment]
I changed my mind, it would be useful. How about some when request content-type is JSON show first 1kB?

**Comment by mzk** [comment]
I solved in BasePresenter.. 
//example
```php
try {
	$_SERVER['API_REQUEST'] = Json::decode($this->getHttpRequest()->getRawBody(), Json::FORCE_ARRAY); //for Tracy log
} catch (JsonException $e) {
	//solve in another place
}
```

`$_SERVER` is dumped in tracy by default.

**Pull request closed without merging**
