### PR TITLE
Add note about using Tracy with CSP

### PR DESCRIPTION
**Pull request by spaze**
This note should make developer's life a bit easier.

### CODE REVIEW

**Comment by enumag** [comment]
:+1:

**Comment by spaze** [comment]
The same note in docs: https://github.com/nette/web-content/pull/421
and at tracy.nette.org: https://github.com/nette/web-content/pull/422

**Comment by dg** [comment]
Thanks. I'll add it to the bottom of page, because it is in-depth information.

**Comment by spaze** [comment]
@dg Yeah, the bottom of the page is probably a better place. Let me know if I should update my pull requests. Thanks!

**Comment by dg** [comment]
merged a64da50cc92d1cac8b9feed05f80c58249bd0208

**Pull request closed without merging**
