### PR TITLE
PSR-3 adapter

### PR DESCRIPTION
**Pull request by JanTvrdik**
@dg Would you accept PR with PSR-3 adapter? So it would be possible to use any PSR-3 compatible logger (e.g. Monolog) with Tracy, i.e. the following would be possible

~~~php
$psrLogger = new Monolog\Logger(...);
$tracyLogger = new Tracy\Bridges\Psr\PsrLoggerAdapter($psrLogger);
Tracy\Debugger::setLogger($tracyLogger);
~~~

Or we could even apply the adapter automatically, so the following would be possible:

~~~php
$psrLogger = new Monolog\Logger(...);
Tracy\Debugger::setLogger($psrLogger);
~~~

### CODE REVIEW

**Comment by JanTvrdik** [comment]
The issue has been converted to PR with implementation. The tests [failed on Travis](https://travis-ci.org/nette/tracy/jobs/421207087) with and odd error 

> Return value of Tester\Runner\Job::getHeaders() must be of the type array, null returned

which looks like either Tester (cc @milo) or PHP bug.

---

> Is it somehow related to #281 & #283 ?

Not directly, but indirectly, yes.

* `PsrToTracyLoggerAdapter` makes it easy to use any third party PSR-3 logger with Tracy, therefore reducing the need for having `StreamLogger` in Tracy.
* `TracyToPsrLoggerAdapter` makes it easy to use any `Tracy\ILogger` with any library that can log to PSR-3 logger. This makes splitting `Tracy\Logger` to multiple smaller `Tracy\ILogger` implementations even more valuable as it allows for example using `Tracy\BlueScreenLogger` as part one of Monolog handlers.

**Comment by JanTvrdik** [comment]
I restarted the build on Travis by using close-reopen combo and the test now works.

**Comment by f3l1x** [comment]
Cool. 🤗

**Comment by dg** [comment]
Thanks, merged.

**Comment by slischka** [comment]
When will be this released ?

**Comment by mabar** [comment]
Nette 3.0

**Pull request merged**
