### PR TITLE
Bar in session: remove undispatched bars after 60 seconds

### PR DESCRIPTION
**Pull request by matej21**

### CODE REVIEW

**Comment by milo** [comment]
Not sure it is correct solution, but it probably solve my issue. I can find 2MB - 90MB session files with `_tracy|a:3:{s:8:"redirect";N;s:3:"bar"; .....` junk.

**Comment by dg** [comment]
Queue is limited that there could be a maximum of 5 items, so it shouldn't accumulate data… https://github.com/nette/tracy/blob/cf59d9cceb3a9c1ed9253b864dd2498043bbaae5/src/Tracy/Bar.php#L98
@milo can you try to explore what is wrong?

**Comment by JanTvrdik** [comment]
Is it possible that those 5 items could possible never expire?

**Comment by milo** [comment]
@dg Thanks to pointing this code. It takes some sense to me now, even I cannot reproduce it.

My guess is, I made some huge dump (~20MB) by mistake and I stopped loading in a browser, so item wasn't picked up. Than again and again wasn't picked up. Than I fixed this dump, but data remains in the session, because ordinary traffic is one tracy bar, or two on redirection.

**Pull request closed without merging**
