### PR TITLE
panels for too small viewport

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Super cool but unfortunately a BC breaks for every panel that assumed scrollbars on `.tracy-inner`. So for example Nextras Mail Panel is broken by this change.

**Comment by adrianbj** [comment]
@JanTvrdik  - oh yeah - I didn't see that - all my custom panels use tracy-inner like that too. Now the title at the top of the panel scrolls with the content. I actually tried this approach initially when trying to deal with this and came to the same realization :)

**Comment by dg** [comment]
What exactly is the problem?

**Comment by adrianbj** [comment]
There may be more to it in @JanTvrdik's case, but for me it is simply that you can't keep the panel <h1> header sticky at the top because the entire panel is now scrolling, not just tracy-inner. This prevent easy access to by able to move, close, and swap to a popup window without having to scroll to the top of the panel.

**Comment by JanTvrdik** [comment]
@dg I need to have (for Tracy 2.3) reserved space for vertical scrollbar to prevent the ugly horizontal scrollbar.

~~~css
#tracy-debug .tracy-panel.tracy-mode-peek .tracy-inner.nextras-mail-panel,
#tracy-debug .tracy-panel.tracy-mode-float .tracy-inner.nextras-mail-panel {
	overflow-y: scroll;  /* reserve space for scrollbar */
}
~~~

This will make the panel in Tracy 2.4 visually inconsistent with others when viewport is large (because it will keep scrolling on .tracy-inner) and broken with ugly triple scrollbar when viewport is small

image

**Comment by dg** [comment]
@adrianbj  It is intention because in small viewport header takes big space for itself. Dragging is now possible via border.

**Comment by JanTvrdik** [comment]
> It is intention because in small viewport header takes big space for itself.

The problem is that it makes the header hard to access even when the viewport is large (height 500px+) and the panel scrolls simple because there are lot of data.

**Comment by dg** [comment]
Its pity. I don't know how to solve  #184.

**Comment by adrianbj** [comment]
I am also having the horizontal scroll issue and also agree that you need access to the header all the time.

I think that https://github.com/nette/tracy/issues/184#issuecomment-220625501 is a decent start to the solution - it just also needs to be called when the panel is displayed, not just when the browser is resized.

**Comment by dg** [comment]
Problem it that you cannot define max-width: 500px and max-width: 100hv at the same time.

**Comment by JanTvrdik** [comment]
@dg Just an idea – what about applying `calc(100vh - 22px)` based on media query on height?

**Comment by dg** [comment]
@JanTvrdik YES!

**Comment by JanTvrdik** [comment]
:+1: Work quite well. Now I'm just not sure whether we need the first commit

**Comment by adrianbj** [comment]
I am finding that I need 75, rather than 25:
```
max-height: calc(100vh - 75px);
```
It is still hidden behind the debug bar, but at least if you move left of the bar, you can see it all. With 25 I still have 50x below the bottom of the viewport.

Chrome/OSX

**Comment by JanTvrdik** [comment]
@adrianbj The updated commit uses `55px`. It assumes that outside of `.tracy-inner` is only a single `<h1>` element.

**Comment by adrianbj** [comment]
With `55px` I still can't see the bottom of the panel.

screen shot 2016-05-21 at 12 37 14 pm

That's the unmodified System Info which only has a single `<h1>`

I just checked on Firefox and it actually looks ok.

The other problem highlighted by that screenshot is that when vertical scrollbar appears, the horizontal one also kicks in.

**Comment by JanTvrdik** [comment]
> I still can't see the bottom of the panel.

That's because of the horizontal scrollbar. The only reliable solution AFAIK is to add `overflow-y: scroll` to `.tracy-inner`.

**Comment by adrianbj** [comment]
Actually it's not just because of the horizontal scrollbar - here it is in firefox - scrollbar is there, but you can still see the bottom of the panel - note the rounded corners that can't be seen in the Chrome screenshot.

screen shot 2016-05-21 at 12 56 52 pm

**Comment by dg** [comment]
@adrianbj can you try to set overflow-y: scroll to .tracy-inner ?

**Comment by adrianbj** [comment]
Obviously that gets rid of the horizontal scrollbar, but it still doesn't let me see the bottom of the panel in Chrome.

**Comment by dg** [comment]
55px works fine in my Chrome 51 on Windows, your Firefox on Mac, but it is different on your Chrome/Mac, right? And headers are exatly the same in both pictures. Weird…

**Pull request merged**
