### PR TITLE
Debugger::enable(): Fix broken autoload [bug]

### PR DESCRIPTION
**Pull request by janbarasek**
- bug fix
- BC break? no

While installing Nette Sandbox in Docker, I noticed that in some cases autoload may not be available and classes may not load correctly.

The original implementation goes through an array of strings, but they are not used anywhere and only loads the Debugger each time:

Screenshot from 2021-03-01 15-26-48

The original implementation used a non-existent path (logic error):

Screenshot from 2021-03-01 15-26-37

Now I have fixed the whole problem.

Thanks.

### CODE REVIEW

**Comment by dg** [comment]
I don't understand what it solves.

**Comment by janbarasek** [comment]
@dg When a Tracy instance was called during the Composer autoload task (and the autoloader has not yet been built), in some cases it was not possible to load all the files. This MR fixes loading all classes correctly (previously there was an error in the file path).

**Comment by janbarasek** [comment]
Problem is here (because you ignore iterated classes and always load only the Debugger):

Screenshot from 2021-03-08 15-59-59

**Comment by dg** [comment]
What?

https://github.com/nette/tracy/blob/0c13775ea0d3b681ae1d9bea59ed94029a96c09d/src/Tracy/Debugger/Debugger.php#L212

**Comment by janbarasek** [comment]
Oh, I'm so sorry! I debugged Tracy on the legacy project where this error occurs (screenshot comes from that project). :/

**Comment by dg** [comment]
@mesour found out that PHPStorm is causing this.

**Pull request closed without merging**
