### PR TITLE
vector icons 

### PR DESCRIPTION
**Pull request by dg**
Vector icons. Colors can be changed.
See #97

### CODE REVIEW

**Comment by hrach** [comment]
I have no idea what is the second icon. Also I don't like the box for session. I liked more the dollar sign icon for dumps, but the eye is ok.

**Comment by dg** [comment]
Second icon is Dependency Injection container. And feel free to suggest better icons.

**Comment by hrach** [comment]
- Session: what about something like folder? http://fontawesome.io/icon/folder-open/
- DIC: this http://fontawesome.io/icon/tasks? it remindes me defition list.

**Comment by dg** [comment]
Btw, we are absolutely not limited to fontawesome.io

**Comment by dg** [comment]
Zoomed:

**Comment by hrach** [comment]
What about removing the "opacity overlay" for previous render and fixing the the bg glitch on the right side? :o)

**Comment by medhi** [comment]
For session, I suggest a chair.
tracy-kreslo

**Comment by dg** [comment]
Good idea :-)

**Comment by hrach** [comment]
I think, that we can strip "session" label <= chair is awesome! :-)

**Comment by fprochazka** [comment]
Chair is lovely :)

**Comment by dg** [comment]
Can you send link to chair?

**Comment by medhi** [comment]
Home made :)

https://gist.github.com/medhi/cab98cdfd9be83964d4b#file-chair-svg

**Comment by medhi** [comment]
And here I tried to create a container with some injection :) Alternative could be injection itself or just some type of container bin.
tracy-kreslo-di

**Comment by medhi** [comment]
:+1:

**Comment by hrach** [comment]
I liked more the blue graph, this icons seems more like signal strenght than graph.

**Comment by fprochazka** [comment]
The dollar sign was nicer. The DIC is interesting, I guess we won't be needing title for that one :) saved space ftw.

**Comment by medhi** [comment]
Maybe better without the gradient on the bar graph.

@hrach Quite, but signal icon has always the bars in the incremental order. But I agree, that previous icon was more clear.

**Comment by dg** [comment]
ad blue vs orange: I like more blue too (obviously, my favourite color), but Bar usually will contain these items and Route is blue too:

untitled-2

ad signal strengh: maybe last column can be lower

ad dollar sign: it is not variables, it is dumps

**Comment by medhi** [comment]
Yes, blue is better. Make the route icon darker: #3A404A

**Comment by dg** [comment]
What about this:
untitled-2

**Comment by dg** [comment]
I am not still sure with pink database ;-)

**Comment by medhi** [comment]
Coloured graph looks little bit messy. Database should has been violet. I don't know, from what I remember it from, it so long. Old times :)

**Comment by dg** [comment]
New icons are merged, you can check them in sandbox.

**Comment by dg** [comment]
One more thing: route icon looks good on retina display, but on other displays it is heavy A. Maybe we should find anoter icon. Maybe something with arrow? Like https://github.com/nette/tracy/issues/97#issuecomment-73431224

**Comment by medhi** [comment]
https://www.iconfinder.com/icons/200504/arrows_directional_signs_two_icon#size=128
https://www.iconfinder.com/icons/200507/arrows_directional_divide_opus_signs_two_icon#size=128

**Comment by dg** [comment]
Btw this https://www.iconfinder.com/icons/200508/arrows_directional_signs_two_way_icon#size=128 looks in low resolution like coitus ;-)

**Comment by medhi** [comment]
Ok, we found an icon looking like a coitus. At least one achievement of our night discussion :)

**Comment by dg** [comment]
:-))

**Comment by dg** [comment]
untitled-2

**Comment by eugeene** [comment]
neat!

**Comment by hrach** [comment]
I would like to see time by default, please! :-)

**Comment by eugeene** [comment]
I can see the time by default

**Comment by hrach** [comment]
Yes, sorry, I just saw tweet, which says it is elastic, which probably means it's responsive :-)

**Comment by dg** [comment]
This screenshot is taken with `.tracy-label {display: none;}` and big zoom. I wanted to emphasize new icons.

But even so is the new Tracy shorter.

**Comment by medhi** [comment]
Red "logout" icon and one icon with gradient? I really don't like it, but still better than old bitmap icons :)

**Comment by dg** [comment]
Does it look like logout?

**Comment by medhi** [comment]
Reversed logout :)

**Comment by hrach** [comment]
It looks like exit. https://www.google.com/search?q=exit+icon&source=lnms&tbm=isch&sa=X&ei=qefZVLSeKNPkaMq6goAC&ved=0CAgQ_AUoAQ&biw=1600&bih=763

**Comment by dg** [comment]
It is simply the same icon as the older bitmap one. We can change it.

**Comment by mancze** [comment]
I just really hate that gradient on graph icon. From where did it come? Every other icon is flat and this is THE one which has gradient.

I don't like the exit icon neither but at least it is just vectorized version of the old icon so it makes some sense.

**Comment by dg** [comment]
All icons are flat, some of them has more colors or shades.

**Comment by vojtech-dobes** [comment]
To be honest, I love the gradient.

**Comment by mrtnzlml** [comment]
This is nice! Now it's time to redesign also panels right? Not just bar... (-:

Just one thing. There was Nette version on Tracy logo hover in previous bar. It was great. But in the new one, there is just Tracy version. Is that mistake or not?

**Comment by george-oakling** [comment]
@mrtnzlml - Tracy is indipendent on Nette, versioning is displayed only for it - its logical...it shloudnt be problem to implement an extension to show Nette version, but for me, it would be nonsense. Tracy version is what matters on Tracy toolbar :)

**Comment by eugeene** [comment]
@george-oakling it is, but, in my opinion, it is better to show Tracy version when used stand-alone, but show Nette version when used /w framework.

**Comment by dg** [comment]
@mrtnzlml it will be visible in next RC (https://github.com/nette/bootstrap/commit/6ef8507bccdd3ebe0fdd2aefed17a3ea53015a62)

**Pull request merged**
