### PR TITLE
Bar: info bar show HHVM version if is running on HHVM

### PR DESCRIPTION
**Pull request by Vrtak-CZ**

### CODE REVIEW

**Comment by hrach** [comment]
Better not to add hhvm key if it's not running under hhvm.

**Comment by Majkl578** [comment]
@hrach: :+1: 
Same for PHP.

**Comment by Vrtak-CZ** [comment]
@hrach @Majkl578 is in `array_filter` https://github.com/nette/tracy/blob/master/src/Tracy/assets/Bar/info.panel.phtml#L14

**Comment by hrach** [comment]
@Vrtak-CZ oh, sorry, obviously 3 lines around isn't enough :)

**Comment by Majkl578** [comment]
@Vrtak-CZ: PHP will not be filtered.

**Pull request merged**
